[general]
import = [
    "~/.config/alacritty/themes/gruvbox_material.toml"
]

[env]
TERM = "tmux-256color"

[window]
padding.x = 25
padding.y = 25

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "Iosevka Nerd Font"
size = 16 

