[general]
import = [
    "~/.config/alacritty/themes/gruvbox_material.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 25
padding.y = 25

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
size = 16 

