[general]
import = [
    "~/.config/alacritty/themes/kanagawa.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
size = 14

